### ISSUE TITLE
TypeCase处理中文出错

### ISSUE THREAD

**Issue by huangzworks** [huangzworks/ooredis#2]
TypeCase类的unicode编码没有处理好，待修复。

```
>>> greet = SingleValue('greet')
>>> greet.set('你好')
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/lib/python2.7/site-packages/ooredis/mix/string.py", line 48, in set
    value = self._type_case.to_redis(value)
    File "/usr/lib/python2.7/site-packages/ooredis/type_case.py", line 14, in to_redis
    value = unicode(value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
>>> greet.set(u'你好')
>>> greet.get()
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/lib/python2.7/site-packages/ooredis/mix/string.py", line 69, in get
    return self._type_case.to_python(value)
    File "/usr/lib/python2.7/site-packages/ooredis/type_case.py", line 42, in to_python
        raise ValueError
ValueError
```

**Comment by huangzworks** [comment]
ff3d53e 已修复
